config/routes.rb
Rails.application.routes.draw do
  get '/user/info' ,to: 'user#info'
  devise_for :users
  root to: "home#index"
  resources :publications, only: [:index, :show]
  namespace :admin do
  	resources :publications
  end 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/publication.rb
class Publication < ApplicationRecord
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
   has_one :subscription
   devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   after_create :create_subscription
   def create_subscription 
     Subscription.create(user_id: id) if subscription.nil?
   end 

end

app/controllers/admin/publications_controller.rb
class Admin::PublicationsController < AdminController 
	before_action :find_publication, only: [:show, :edit,:update ,:destroy]

	def index 
		@publications = Publication.all
	end 

	def show

	end 

	def new 
		@publications = Publication.new 
	end 

	def create 
		@publications = Publication.new(publication_params)
		if @publications.save 
			redirect_to admin_publication_path(@publications)
		else 
			render :new, alert: "Something went wrong"
		end 
	end 

	def edit

	end 

	def update 
		if @publications.update(publication_params)
			redirect_to admin_publication_path(@publications)
		else 
			render :edit,alert: "Something went wrong"
		end 
	end 

	def destroy 
		@publications.destroy
		redirect_to admin_publication_path,alert: "Succefully deleted publication"
	end 

	private 
	def find_publication
		@publications = Publication.find(params[:id])
	end 

	def publication_params
		params.require(:publication).permit(:title, :description, :file_url)
	end
end 

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :check_for_admin 
	def check_for_admin
		if current_user.nil? || !current_user.is_admin?
			redirect_to root_path, alert: "You must be admin to acces this path"
		end 
	end 
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
	def index 
		@publications = Publication.all 
	end 

	def show 
		@publications = Publication.find(params[:id])
	end 
end 

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!
  def info
  	@subscription  = current_user.subscription
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/publications/edit.html.erb
<h3> Edit <%= @publications.title %> </h3>
<%= form_for @publications, url: admin_publication_path(@publications) do |f| %>
	<div class="form-group">
		<label> Title </label>
		<%= f.text_field :title,class: "form-control"
		%>
	</div>
	<div class="form-group">
		<label>File URL </label>
		<%= f.text_field :file_url,class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.submit "update Publication",class: 'btn btn-primary' %>
	</div>
	<% end %>

app/views/admin/publications/index.html.erb
<h2>Publication </h2>
<div>

<%= link_to "New publication", 
new_admin_publication_path, class: 'btn btn-primary'
%>
</div>
<% @publications.each do |publication| %>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title"><%= publication.title %>
			</h3>
		</div>
		<div class="panel-body">
	      <p><%= publication.description %> </p>
	      <p> <%= publication.file_url %> </p>
	    </div>

	    <div class="panel-footer">
	    	<%= link_to "View more details",
	    	admin_publication_path(publication),class: "btn btn-default" %>
	    	<%= link_to "Edit",
	    	edit_admin_publication_path(publication),class: "btn btn-default" %>
	    </div>
	 </div>
<% end %>

app/views/admin/publications/new.html.erb
<h3> New Publication path </h3>
<%= form_for @publications, url: admin_publications_path do |f| %>
	<div class="form-group">
		<label> Title </label>
		<%= f.text_field :title,class: "form-control"
		%>
	</div>
	<div class="form-group">
		<label>File URL </label>
		<%= f.text_field :file_url,class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.submit "update Publication",class: 'btn btn-primary' %>
	</div>
<% end %>

app/views/admin/publications/show.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title"> <%= @publications.title 
		%> </h3>
	</div>
	<div class="panel-body">
		<p> <%= @publications.description %> </p>
		<p> <%= @publications.file_url %> </p>
	</div>
</div>

app/views/application/_nav.html.erb
<!-- <nav class="navbar navbar-dark bg-dark"> -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">subscription</a>
   
    <div class="collapse navbar-collapse" id="navbarNav">
      
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <a href="#"> Sign in as <%= current_user.email %> </a>
          </li>
          <li class="nav-item">
            <%= link_to "Sign out", destroy_user_session_path,method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign in",new_user_session_path %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up",new_user_registration_path %>
          </li>
        <% end %>
      
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1> Hello world</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SubscriptionApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/css/bootstrap.min.css" integrity="sha384-DhY6onE6f3zzKbjUPRc2hOzGAdEf4/Dz+WJwBvEYL/lkkIsI3ihufq9hk9K4lVoK" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'nav' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/publications/index.html.erb
<h2>Publication </h2>

<% @publications.each do |publication| %>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title"> <%= publication.title %></h3>
	</div>
	<div class="panel-body">
		<p><%= publication.description %></p>
		<p><%= publication.file_url %></p>
	</div>
	<div class="panel-footer">
		<%= link_to "View more details",
		publication_path(publication), class: "btn btn-default" %>
	</div>
 </div>
<% end %>

app/views/publications/show.html.erb
<h2>Publication </h2>

<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title"> <%= @publications.title %></h3>
	</div>
	<div class="panel-body">
		<p><%= @publications.description %></p>
		<p><%= @publications.file_url %></p>
	</div>
 </div>

app/views/user/info.html.erb
<h1>User#info</h1>
<p>Find me in app/views/user/info.html.erb</p>
<%= current_user.email %>
<%if @subscription.active %>
	"subscribe"
<% else %>
    "unsubscribe"
<% end %>